#!/usr/bin/env python3
"""Generate deterministic OBJ assets for the transport-scene fruit props.

The visual meshes are smooth and recognisable. The collision meshes are much
smaller convex pieces: one hull each for the apple, orange and pear, plus five
overlapping flat-sided segments for the banana. Keeping these representations
separate is important for stable gripper contact and fast MuJoCo stepping.

Run from anywhere:

    python scripts/generate_transport_prop_meshes.py
"""
from __future__ import annotations

import math
import pathlib
from typing import Iterable, Sequence


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT_DIR = (
    REPO_ROOT
    / "src/rby1_description/models/rby1a/mujoco/assets/transport_props"
)

Vec3 = tuple[float, float, float]
Face = tuple[int, int, int]


def _add(a: Vec3, b: Vec3) -> Vec3:
    return a[0] + b[0], a[1] + b[1], a[2] + b[2]


def _scale(v: Vec3, s: float) -> Vec3:
    return v[0] * s, v[1] * s, v[2] * s


def _write_obj(path: pathlib.Path, vertices: Sequence[Vec3], faces: Iterable[Face], description: str) -> None:
    lines = [
        "# Generated by scripts/generate_transport_prop_meshes.py",
        f"# {description}",
        "# Units: metres; project-owned procedural asset (MIT)",
        "o " + path.stem,
    ]
    lines.extend(f"v {x:.9f} {y:.9f} {z:.9f}" for x, y, z in vertices)
    lines.extend(f"f {a + 1} {b + 1} {c + 1}" for a, b, c in faces)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _latlong_surface(
    n_lat: int,
    n_lon: int,
    point,
) -> tuple[list[Vec3], list[Face]]:
    """Closed UV surface with singular top/bottom vertices."""
    vertices = [point(0.0, 0.0)]
    for i in range(1, n_lat):
        theta = math.pi * i / n_lat
        for j in range(n_lon):
            vertices.append(point(theta, 2.0 * math.pi * j / n_lon))
    bottom = len(vertices)
    vertices.append(point(math.pi, 0.0))

    faces: list[Face] = []
    first = 1
    for j in range(n_lon):
        faces.append((0, first + j, first + (j + 1) % n_lon))
    for i in range(n_lat - 2):
        ring = 1 + i * n_lon
        next_ring = ring + n_lon
        for j in range(n_lon):
            a = ring + j
            b = ring + (j + 1) % n_lon
            c = next_ring + j
            d = next_ring + (j + 1) % n_lon
            faces.extend(((a, c, d), (a, d, b)))
    last = 1 + (n_lat - 2) * n_lon
    for j in range(n_lon):
        faces.append((last + j, bottom, last + (j + 1) % n_lon))
    return vertices, faces


def _apple_point(theta: float, phi: float, *, lobed: bool) -> Vec3:
    # Broad shoulders, a slightly tapered base and five subtle apple lobes.
    sin_t = math.sin(theta)
    z = 0.0305 * math.cos(theta)
    profile = math.pow(max(sin_t, 0.0), 0.78)
    shoulder = 0.94 + 0.10 * sin_t - 0.035 * math.cos(theta)
    lobe = 1.0 + (0.045 * math.cos(5.0 * phi) * sin_t * sin_t if lobed else 0.0)
    radius = 0.0325 * profile * shoulder * lobe
    # Pull in the crown so the stem grows from a visible dimple.
    if z > 0.021:
        radius *= 0.86 + 0.14 * (0.0305 - z) / 0.0095
    return radius * math.cos(phi), radius * math.sin(phi), z


def _make_apple() -> None:
    vertices, faces = _latlong_surface(
        24, 48, lambda theta, phi: _apple_point(theta, phi, lobed=True)
    )
    _write_obj(
        OUTPUT_DIR / "apple_visual.obj",
        vertices,
        faces,
        "Five-lobed smooth apple visual mesh",
    )

    vertices, faces = _latlong_surface(
        7, 12, lambda theta, phi: _apple_point(theta, phi, lobed=False)
    )
    _write_obj(
        OUTPUT_DIR / "apple_collision.obj",
        vertices,
        faces,
        "Low-poly convex apple collision hull",
    )


def _orange_point(theta: float, phi: float, *, textured: bool) -> Vec3:
    sin_t = math.sin(theta)
    z = 0.0295 * math.cos(theta)
    peel = 1.0 + (0.014 * math.cos(8.0 * phi) * sin_t * sin_t if textured else 0.0)
    radius = 0.0315 * math.pow(max(sin_t, 0.0), 0.96) * peel
    # Shallow dimples at the calyx and navel make it less sphere-like.
    if abs(z) > 0.024:
        radius *= 0.94
    return radius * math.cos(phi), radius * math.sin(phi), z


def _make_orange() -> None:
    vertices, faces = _latlong_surface(
        22, 44, lambda theta, phi: _orange_point(theta, phi, textured=True)
    )
    _write_obj(
        OUTPUT_DIR / "orange_visual.obj",
        vertices,
        faces,
        "Slightly flattened orange visual mesh with subtle peel ribs",
    )

    vertices, faces = _latlong_surface(
        7, 12, lambda theta, phi: _orange_point(theta, phi, textured=False)
    )
    _write_obj(
        OUTPUT_DIR / "orange_collision.obj",
        vertices,
        faces,
        "Low-poly convex orange collision hull",
    )


def _make_orange_calyx() -> None:
    # Closed ten-point star prism, slightly above the orange crown.
    vertices: list[Vec3] = []
    for z in (0.0290, 0.0302):
        for i in range(10):
            angle = 2.0 * math.pi * i / 10.0
            radius = 0.0080 if i % 2 == 0 else 0.0032
            vertices.append((radius * math.cos(angle), radius * math.sin(angle), z))
    bottom_center, top_center = len(vertices), len(vertices) + 1
    vertices.extend(((0.0, 0.0, 0.0290), (0.0, 0.0, 0.0302)))
    faces: list[Face] = []
    for i in range(10):
        nxt = (i + 1) % 10
        faces.append((bottom_center, nxt, i))
        faces.append((top_center, 10 + i, 10 + nxt))
        faces.extend(((i, nxt, 10 + nxt), (i, 10 + nxt, 10 + i)))
    _write_obj(
        OUTPUT_DIR / "orange_calyx_visual.obj",
        vertices,
        faces,
        "Green star-shaped orange calyx visual mesh",
    )


def _pear_point(theta: float, phi: float, *, textured: bool) -> Vec3:
    sin_t = math.sin(theta)
    cos_t = math.cos(theta)
    z = 0.0025 + 0.0385 * cos_t  # top +41 mm, bottom -36 mm
    profile = math.pow(max(sin_t, 0.0), 0.82)
    # Narrow neck above the centre and broad, load-stable lower shoulder.
    asymmetry = 1.0 - 0.30 * cos_t
    ripple = 1.0 + (0.018 * math.cos(7.0 * phi) * sin_t * sin_t if textured else 0.0)
    radius = 0.0290 * profile * asymmetry * ripple
    return radius * math.cos(phi), radius * math.sin(phi), z


def _make_pear() -> None:
    vertices, faces = _latlong_surface(
        26, 48, lambda theta, phi: _pear_point(theta, phi, textured=True)
    )
    _write_obj(
        OUTPUT_DIR / "pear_visual.obj",
        vertices,
        faces,
        "Asymmetric pear visual mesh with narrow neck and broad base",
    )

    vertices, faces = _latlong_surface(
        9, 14, lambda theta, phi: _pear_point(theta, phi, textured=False)
    )
    _write_obj(
        OUTPUT_DIR / "pear_collision.obj",
        vertices,
        faces,
        "Low-poly convex pear collision hull",
    )


def _tube_surface(centres: Sequence[Vec3], radii: Sequence[tuple[float, float]], sides: int) -> tuple[list[Vec3], list[Face]]:
    """Tube along an x-z centreline; radii are (y, normal-to-curve)."""
    vertices: list[Vec3] = []
    normals: list[Vec3] = []
    for i, centre in enumerate(centres):
        if i == 0:
            tangent = _add(centres[1], _scale(centre, -1.0))
        elif i == len(centres) - 1:
            tangent = _add(centre, _scale(centres[i - 1], -1.0))
        else:
            tangent = _add(centres[i + 1], _scale(centres[i - 1], -1.0))
        length = math.hypot(tangent[0], tangent[2])
        tx, tz = tangent[0] / length, tangent[2] / length
        normals.append((-tz, 0.0, tx))
        ry, rn = radii[i]
        for j in range(sides):
            angle = 2.0 * math.pi * j / sides
            ridge = 1.0 + 0.035 * math.cos(5.0 * angle)
            y = ry * math.cos(angle) * ridge
            n = rn * math.sin(angle) * ridge
            vertices.append(_add(centre, _add((0.0, y, 0.0), _scale(normals[-1], n))))

    faces: list[Face] = []
    for i in range(len(centres) - 1):
        ring = i * sides
        next_ring = ring + sides
        for j in range(sides):
            a = ring + j
            b = ring + (j + 1) % sides
            c = next_ring + j
            d = next_ring + (j + 1) % sides
            faces.extend(((a, b, d), (a, d, c)))

    left_centre = len(vertices)
    vertices.append(centres[0])
    right_centre = len(vertices)
    vertices.append(centres[-1])
    last_ring = (len(centres) - 1) * sides
    for j in range(sides):
        nxt = (j + 1) % sides
        faces.append((left_centre, nxt, j))
        faces.append((right_centre, last_ring + j, last_ring + nxt))
    return vertices, faces


def _banana_centre(s: float) -> Vec3:
    return 0.0355 * s, 0.0, -0.003 + 0.011 * s * s


def _banana_radius(s: float) -> tuple[float, float]:
    # Full-size centre section where the gripper closes, then a linear taper.
    # Segment boundaries at |s|=0.2/0.6 make the convex decomposition track it.
    fullness = min(1.0, max(0.0, (1.0 - abs(s)) / 0.8))
    return 0.0095 + 0.0120 * fullness, 0.0065 + 0.0135 * fullness


def _banana_collision_piece(lo: float, hi: float) -> tuple[list[Vec3], list[Face]]:
    """Tapered convex segment with flat gripper-facing y sides."""
    vertices: list[Vec3] = []
    for sx, sy, sz in (
        (-1, -1, -1), (1, -1, -1), (1, 1, -1), (-1, 1, -1),
        (-1, -1, 1), (1, -1, 1), (1, 1, 1), (-1, 1, 1),
    ):
        s = lo if sx < 0 else hi
        centre = _banana_centre(s)
        # Analytic tangent of the parabolic centreline.
        dx, dz = 0.0355, 0.022 * s
        length = math.hypot(dx, dz)
        normal = (-dz / length, 0.0, dx / length)
        ry, rn = _banana_radius(s)
        # Small collision skin encloses the quadratic centreline between each
        # pair of end sections and prevents the visual surface entering a table.
        ry += 0.0005
        rn += 0.0008
        vertices.append(_add(centre, _add((0.0, sy * ry, 0.0), _scale(normal, sz * rn))))
    faces = [
        (0, 3, 2), (0, 2, 1), (4, 5, 6), (4, 6, 7),
        (0, 1, 5), (0, 5, 4), (3, 7, 6), (3, 6, 2),
        (0, 4, 7), (0, 7, 3), (1, 2, 6), (1, 6, 5),
    ]
    return vertices, faces


def _make_banana() -> None:
    samples = 29
    ss = [-1.0 + 2.0 * i / (samples - 1) for i in range(samples)]
    vertices, faces = _tube_surface(
        [_banana_centre(s) for s in ss],
        [_banana_radius(s) for s in ss],
        20,
    )
    _write_obj(
        OUTPUT_DIR / "banana_visual.obj",
        vertices,
        faces,
        "Curved, tapered and subtly ridged banana visual mesh",
    )

    # Overlap neighbouring pieces by 0.8 mm to avoid collision cracks.  Unlike a
    # single mesh (which MuJoCo convexifies), this decomposition follows the bend.
    bounds = [-1.0, -0.60, -0.20, 0.20, 0.60, 1.0]
    for index, (lo, hi) in enumerate(zip(bounds, bounds[1:])):
        overlap_s = 0.0008 / 0.0355
        piece_lo = max(-1.0, lo - (overlap_s if lo > -1.0 else 0.0))
        piece_hi = min(1.0, hi + (overlap_s if hi < 1.0 else 0.0))
        vertices, faces = _banana_collision_piece(piece_lo, piece_hi)
        _write_obj(
            OUTPUT_DIR / f"banana_collision_{index}.obj",
            vertices,
            faces,
            f"Convex banana collision segment {index + 1}/5",
        )


def _make_banana_tips() -> None:
    all_vertices: list[Vec3] = []
    all_faces: list[Face] = []
    for s in (-1.0, 1.0):
        dx, dz = 0.0355, 0.022 * s
        length = math.hypot(dx, dz)
        tangent = (dx / length, 0.0, dz / length)
        outward = _scale(tangent, s)
        normal = (-tangent[2], 0.0, tangent[0])
        center = _add(_banana_centre(s), _scale(outward, 0.0010))

        def point(theta: float, phi: float) -> Vec3:
            along = 0.0022 * math.cos(theta)
            radial = math.sin(theta)
            return _add(
                center,
                _add(
                    _scale(outward, along),
                    _add(
                        (0.0, 0.0096 * radial * math.cos(phi), 0.0),
                        _scale(normal, 0.0066 * radial * math.sin(phi)),
                    ),
                ),
            )

        vertices, faces = _latlong_surface(8, 16, point)
        offset = len(all_vertices)
        all_vertices.extend(vertices)
        all_faces.extend((a + offset, b + offset, c + offset) for a, b, c in faces)
    _write_obj(
        OUTPUT_DIR / "banana_tips_visual.obj",
        all_vertices,
        all_faces,
        "Brown banana end-cap visual mesh",
    )


def _make_stem() -> None:
    centres = []
    radii = []
    for i in range(7):
        t = i / 6.0
        centres.append((0.001 + 0.004 * t * t, 0.0, 0.027 + 0.021 * t))
        radius = 0.0031 - 0.0010 * t
        radii.append((radius, radius))
    vertices, faces = _tube_surface(centres, radii, 10)
    _write_obj(
        OUTPUT_DIR / "apple_stem_visual.obj",
        vertices,
        faces,
        "Tapered, slightly curved apple stem visual mesh",
    )


def _make_pear_stem() -> None:
    centres = []
    radii = []
    for i in range(7):
        t = i / 6.0
        centres.append((0.001 + 0.003 * t * t, 0.0, 0.038 + 0.020 * t))
        radius = 0.0026 - 0.0008 * t
        radii.append((radius, radius))
    vertices, faces = _tube_surface(centres, radii, 10)
    _write_obj(
        OUTPUT_DIR / "pear_stem_visual.obj",
        vertices,
        faces,
        "Tapered pear stem visual mesh",
    )


def _make_leaf() -> None:
    angle = math.radians(24.0)
    ux = (math.cos(angle), math.sin(angle), 0.18)
    ul = math.sqrt(sum(v * v for v in ux))
    ux = tuple(v / ul for v in ux)
    uy = (-math.sin(angle), math.cos(angle), 0.0)
    uz = (
        ux[1] * uy[2] - ux[2] * uy[1],
        ux[2] * uy[0] - ux[0] * uy[2],
        ux[0] * uy[1] - ux[1] * uy[0],
    )
    center = (0.011, 0.003, 0.038)

    def point(theta: float, phi: float) -> Vec3:
        local = (
            0.014 * math.sin(theta) * math.cos(phi),
            0.0055 * math.sin(theta) * math.sin(phi),
            0.0010 * math.cos(theta),
        )
        return _add(center, _add(_scale(ux, local[0]), _add(_scale(uy, local[1]), _scale(uz, local[2]))))

    vertices, faces = _latlong_surface(8, 20, point)
    _write_obj(
        OUTPUT_DIR / "apple_leaf_visual.obj",
        vertices,
        faces,
        "Thin apple leaf visual mesh",
    )


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    _make_apple()
    _make_stem()
    _make_leaf()
    _make_banana()
    _make_banana_tips()
    _make_orange()
    _make_orange_calyx()
    _make_pear()
    _make_pear_stem()
    print(f"generated 17 OBJ files in {OUTPUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
